services:
  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: